kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: runguard
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8088
        protocol: TCP
  - role: worker
  - role: worker
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
