apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "runguard.fullname" . }}-job-controller
  labels:
    {{- include "runguard.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runguard.fullname" . }}-job-controller
  labels:
    {{- include "runguard.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runguard.fullname" . }}-job-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "runguard.fullname" . }}-executor
  labels:
    {{- include "runguard.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    {{- with .Values.config.targetInventory }}
    resourceNames:
      {{- range $service, $target := . }}
      - {{ required (printf "config.targetInventory.%s.name is required" $service) $target.name | quote }}
      {{- end }}
    {{- end }}
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runguard.fullname" . }}-executor
  labels:
    {{- include "runguard.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.executorServiceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runguard.fullname" . }}-executor
