{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "runguard.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
---
{{- if .Values.executorServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.executorServiceAccount.name }}
  labels:
    {{- include "runguard.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
