{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "runguard.fullname" . }}
  labels:
    {{- include "runguard.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "runguard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.config.protectDiagnostics }}
      authorization:
        type: Bearer
        credentials:
          name: {{ .Values.secrets.existingSecret | default (include "runguard.fullname" .) }}
          key: RUNGUARD_DIAGNOSTICS_TOKEN
      {{- end }}
{{- end }}
