from __future__ import annotations

from typing import Any

from .models import PostmortemDocument
from .store import Store


class PostmortemService:
    def __init__(self, store: Store) -> None:
        self.store = store

    def generate(
        self,
        incident_id: str,
        reporter_output: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        incident = self.store.get_incident(incident_id)
        hypotheses = incident.get("hypotheses", [])
        root_cause = (
            hypotheses[0]["cause"]
            if hypotheses
            else "Root cause remains unconfirmed; further human investigation is required."
        )
        evidence = incident.get("evidence", [])
        events = incident.get("events", [])
        intents = incident.get("tool_intents", [])
        report = reporter_output or {}
        timeline = [
            {
                "at": event["created_at"],
                "event": event["event_type"],
                "actor": event["actor"],
                "detail": self._event_detail(event),
            }
            for event in events
        ]
        remediation = [
            (
                f"{intent['tool_name']} on "
                f"{intent.get('resource', {}).get('name', incident['service'])} "
                f"({intent['status']})"
            )
            for intent in intents
        ] or ["No infrastructure mutation was executed."]
        document = PostmortemDocument(
            incident_id=incident_id,
            run_id=incident.get("current_run_id"),
            title=f"{incident_id}: {incident['title']}",
            summary=report.get(
                "summary",
                (
                    f"{incident['service']} entered {incident['status']} after a "
                    f"{incident['severity']} incident in {incident['environment']}."
                ),
            ),
            impact=report.get(
                "impact",
                incident.get("description") or "Impact was limited to the affected service.",
            ),
            root_cause=root_cause,
            contributing_factors=report.get(
                "contributing_factors",
                [
                    item["title"]
                    for item in evidence
                    if item.get("title")
                ][:6],
            ),
            timeline=timeline,
            remediation=remediation,
            action_items=report.get(
                "action_items",
                [
                    {
                        "title": "Add a regression alert for the verified failure signal",
                        "owner": "SRE",
                        "priority": "P1",
                        "status": "OPEN",
                    },
                    {
                        "title": "Add the remediation and rollback path to the service runbook",
                        "owner": incident["service"],
                        "priority": "P2",
                        "status": "OPEN",
                    },
                ],
            ),
            lessons=report.get(
                "lessons",
                [
                    "Evidence-linked changes reduce time spent validating competing hypotheses.",
                    "Reversible, bounded remediation should be preferred over broad restarts.",
                ],
            ),
            generated_by=(
                "langgraph-reporter-agent" if reporter_output else "deterministic-reporter-agent"
            ),
        )
        return self.store.upsert_postmortem(incident_id, document.model_dump(mode="json"))

    @staticmethod
    def _event_detail(event: dict[str, Any]) -> str:
        payload = event.get("payload", {})
        if payload.get("from") and payload.get("to"):
            return f"{payload['from']} → {payload['to']}"
        if payload.get("source"):
            return f"source={payload['source']}"
        return ", ".join(f"{key}={value}" for key, value in payload.items())[:300]

    @staticmethod
    def markdown(document: dict[str, Any]) -> str:
        lines = [
            f"# {document['title']}",
            "",
            f"**Status:** {document['status']}",
            f"**Incident:** {document['incident_id']}",
            f"**Run:** {document.get('run_id') or 'n/a'}",
            f"**Generated by:** {document['generated_by']}",
            "",
            "## Executive summary",
            "",
            document["summary"],
            "",
            "## Impact",
            "",
            document["impact"],
            "",
            "## Root cause",
            "",
            document["root_cause"],
            "",
            "## Contributing factors",
            "",
            *[f"- {item}" for item in document["contributing_factors"]],
            "",
            "## Timeline",
            "",
            *[
                f"- `{item['at']}` **{item['actor']}** — {item['event']}: {item['detail']}"
                for item in document["timeline"]
            ],
            "",
            "## Remediation",
            "",
            *[f"- {item}" for item in document["remediation"]],
            "",
            "## Action items",
            "",
            *[
                (
                    f"- [{('x' if item['status'] == 'DONE' else ' ')}] "
                    f"**{item['priority']}** {item['title']} — {item['owner']}"
                )
                for item in document["action_items"]
            ],
            "",
            "## Lessons",
            "",
            *[f"- {item}" for item in document["lessons"]],
            "",
        ]
        return "\n".join(lines)
